In [1]:
import numpy as np
import pandas as pd
from scipy.stats import bernoulli

## Missing Data Management - Probability Question
Construct a database with $100,000$ rows where each record has $100$ fields. Assume further that for each record, each of the $100$ fields has a $1$ per cent chance of being empty, i.e., its value is missing.

Remove all records with **two** or more empty fields and report the fraction of records that are removed.

In [2]:
# Generate and populate a 100000*100 matrix
nr_rows = 100000 
data_to_use = np.ones(nr_rows*100) 
df_exercise = pd.DataFrame(data_to_use.reshape(nr_rows, 100))
df_exercise

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
99996,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
99997,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
99998,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
99999,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [3]:
# Generate indices of missing values
missing_or_not = bernoulli.rvs((1/100), size=nr_rows*100)
missing_or_not = missing_or_not.reshape(nr_rows, 100)

missing_or_not

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [4]:
# Indices of missing row and cols
missing_rows, missing_cols = np.where(missing_or_not == 1)
print(missing_rows, missing_cols,
np.size(missing_rows))

[    1     3     4 ... 99999 99999 99999] [75 22 37 ... 22 37 73] 100227

In [5]:
# Generate np.nan vals for missing rows and cols indices
df_exercise.values[missing_rows, missing_cols] = np.nan

In [6]:
print('In total, there are {} missing values'.format(np.sum(df_exercise.isnull().sum())))

In total, there are 100227 missing values

In [12]:
# Tag the rows that have at least two NaN
df_missing = (df_exercise.isnull().sum(axis = 1) >=2)

# Check implementation 
df_missing, df_exercise.isnull().sum(axis = 1)

(0        False
 1        False
 2        False
 3        False
 4        False
          ...
 99995    False
 99996     True
 99997     True
 99998    False
 99999     True
 Length: 100000, dtype: bool,
 0        0
 1        1
 2        0
 3        1
 4        1
         ..
 99995    0
 99996    2
 99997    2
 99998    1
 99999    4
 Length: 100000, dtype: int64)

In [10]:
print('There are {} rows with at least two missing records'.format(np.sum(df_missing)))
print('If we drop rows with missing values, we lose {} fraction of the whole data'.format(np.sum(df_missing)/nr_rows))

There are 63465 rows with at least two missing records
If we drop rows with missing values, we lose 0.63465 fraction of the whole data